---
runtime: shiny
output: html_document
---

```{r, echo = FALSE}
load(file = "BL.RData")
```

```{r, echo = FALSE}
sliderInput("slider_2a", "Analytical Wavelength (nm)", 
                    min = 400, max = 750, value = 400, step = 1)
checkboxInput("check_2a", label = "Show Model?", value = FALSE)
```

```{r, echo = FALSE}
  renderPlot({
    if (input$check_2a == FALSE) {
        matplot(rawdata$wavelength, 
            as.matrix(rawdata[, c(7, 9, 10, 12, 13, 14)]), 
            type = "l", lty = 1, lwd = 2, col = "blue",
            xlab = "wavelength (nm)", ylab = "absorbance")
    abline(v = input$slider_2a, col = "red", lwd = 2)
    } else {
      conc = std.conc[c(1, 3, 4, 6, 7, 8)]
      abs = as.numeric(rawdata[input$slider_2a - 399, 
                               c(7, 9, 10, 12, 13, 14)])
      plot(conc, abs, pch = 19, cex = 1.2, col = "blue", 
           xlab = "concentration (mM)", ylab = "absorbance")
      abline(lm(abs ~ conc), col = "red", lwd = 2)
    }
  })
reactive({
    if (input$check_2a == TRUE) { 
      conc = std.conc[c(1, 3, 4, 6, 7, 8)]
      abs = as.numeric(rawdata[input$slider_2a - 399, 
                               c(7, 9, 10, 12, 13, 14)])
      summary(lm(abs ~ conc))
    }
  })
```